/**
 * @file sf1r/driver/Keys.inl
 * @date Created <2014-04-24 15:33:58>
 *
 * This file is generated by generators/driver_keys.rb by collecting keys
 * from source code. Do not edit this file directly.
 */

#define SF1_DRIVER_KEYS \
(DOCID)\
(DistributeStatus)\
(MemoryStatus)\
(USERID)\
(_categories)\
(_custom_rank)\
(_duplicated_document_count)\
(_id)\
(_rank)\
(_tid)\
(ad_search)\
(algorithm)\
(analyzer)\
(analyzer_result)\
(apply_la)\
(attr)\
(attr_label)\
(attr_name)\
(attr_result)\
(attr_top)\
(attr_value)\
(attr_values)\
(auto_select_limit)\
(boost_group_label)\
(category)\
(category_score)\
(clear)\
(collection)\
(collection_config)\
(condition_array)\
(conditions)\
(context)\
(count)\
(counter)\
(custom_rank)\
(disable_sharding)\
(document_count)\
(elapsed_time)\
(errors)\
(expression)\
(filter_mode)\
(force_backup)\
(freq)\
(func)\
(fuzzy_threshold)\
(group)\
(group_label)\
(group_property)\
(grouptop)\
(highlight)\
(in)\
(index)\
(index_scd_path)\
(is_random_rank)\
(is_require_related)\
(keywords)\
(label)\
(labels)\
(last_modified)\
(left_time)\
(limit)\
(log_keywords)\
(lucky)\
(max)\
(merchant)\
(meta)\
(min)\
(mining)\
(mode)\
(name)\
(name_entity_item)\
(name_entity_type)\
(offset)\
(operator_)\
(order)\
(original_query)\
(params)\
(pos)\
(privilege_Query)\
(privilege_Weight)\
(progress)\
(property)\
(query)\
(query_prune)\
(query_source)\
(range)\
(rank)\
(ranking_model)\
(recommend)\
(refined_query)\
(related_queries)\
(relation)\
(remote_ip)\
(remove_duplicated_result)\
(resource)\
(resources)\
(score)\
(search)\
(search_session)\
(searching_mode)\
(select)\
(session_id)\
(snippet)\
(sort)\
(split_property_value)\
(status)\
(sub_labels)\
(sub_property)\
(summary)\
(summary_property_alias)\
(summary_sentence_count)\
(taxonomy_label)\
(threshold)\
(tokens_threshold)\
(top_group_label)\
(top_k_count)\
(topn)\
(total_count)\
(type)\
(unit)\
(use_fuzzy)\
(use_fuzzyThreshold)\
(use_original_keyword)\
(use_pivilegeQuery)\
(use_synonym_extension)\
(uuid)\
(value)


/* LOCATIONS

DOCID
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:144
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:146
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:196
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:222
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:670
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:776

DistributeStatus
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:106

MemoryStatus
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:107

USERID
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:156
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:674

_categories
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:178

_custom_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:162

_duplicated_document_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:120

_id
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:139
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:141
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:196
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:214
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:112
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:156

_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:157

_tid
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:127
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:171

ad_search
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:620

algorithm
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:353
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:355

analyzer
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:234

analyzer_result
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:509
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:529

apply_la
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:235

attr
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:243
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:663

attr_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:589

attr_name
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:603
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:269
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/SplitPropValueRenderer.cpp:97

attr_result
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:28
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:30

attr_top
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:33
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:35

attr_value
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:604

attr_values
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/SplitPropValueRenderer.cpp:99

auto_select_limit
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:570

boost_group_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:650

category
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:74
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:31

category_score
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:49
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:23

clear
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:226
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:228

collection
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:169
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:126
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:224
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:301
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:321
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:506
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:580
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:728
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:784
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:842
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:967
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:60
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:88

collection_config
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:843

condition_array
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/ConditionTreeParser.cpp:72

conditions
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:184
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:219

context
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:678
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:680
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:682

count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:183
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:692
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:736
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:771

counter
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:87

custom_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:223
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:226

disable_sharding
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:75

document_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:70
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:85
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:72
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:234
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:240
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:270
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:280

elapsed_time
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:81

errors
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:75
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:96
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:80

expression
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:90
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:91

filter_mode
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:434
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:436

force_backup
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:680

freq
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:565

func
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/SelectFieldParser.cpp:32

fuzzy_threshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:303
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:305

group
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:239
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:658

group_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:525
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:567
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:826
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:840
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:305

group_property
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:813
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:304

grouptop
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:60

highlight
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:182

in
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:455

index
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:67

index_scd_path
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:753
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:77

is_random_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:179

is_require_related
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:180

keywords
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:149
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:799

label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:239
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:279

labels
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:235
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:272

last_modified
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:69
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:86
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:93
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:100

left_time
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:82

limit
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:20
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:22
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:546
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:787
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:789

log_keywords
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:178

lucky
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:412
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:414

max
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:681

merchant
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:25
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:20

meta
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:83

min
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:680

mining
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:91

mode
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:268
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:270

name
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:125

name_entity_item
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:163

name_entity_type
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:164

offset
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:15
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:17

operator_
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:70

order
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/OrderParser.cpp:23

original_query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:425
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:427

params
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:79
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:80

pos
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:682

privilege_Query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:329
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:331

privilege_Weight
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:335
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:337

progress
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:80

property
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:45
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/OrderParser.cpp:22
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/SelectFieldParser.cpp:30
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:181
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:194
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:472
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:539
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:634
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:57
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/RangeParser.cpp:36
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/ConditionTreeParser.cpp:85
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:763
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:233

query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:678

query_prune
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:275
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:275
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:295
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:295

query_source
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:158

range
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:62
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:64
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:247
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:679

rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:680

ranking_model
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:241
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:243

recommend
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:72

refined_query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:704

related_queries
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:653

relation
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/ConditionTreeParser.cpp:73

remote_ip
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:59
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:87

remove_duplicated_result
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:508

resource
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:220
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:285
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:328
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:384
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:425
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:545
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:670
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:674
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:676
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:678
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:680
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:682
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:776
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:797
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:811
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:825
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:839

resources
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:68
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:309
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:328
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:360
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:630
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:641
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:44
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:560

score
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:271
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:281
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:32
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:96
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:21
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:29

search
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:201

search_session
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:98
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:101

searching_mode
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:267

select
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:79
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:215
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:53

session_id
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:157
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:676

snippet
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:196

sort
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:231

split_property_value
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:184

status
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:68
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:76
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:92
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:98

sub_labels
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:241

sub_property
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:58

summary
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:185

summary_property_alias
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:193

summary_sentence_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:189

taxonomy_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:161

threshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:399
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:401

tokens_threshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:314
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:316

top_group_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:668

top_k_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:129

topn
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:74

total_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:68
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:360
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:122

type
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:138

unit
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:59

use_fuzzy
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:430
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:432

use_fuzzyThreshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:300
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:300

use_original_keyword
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:236

use_pivilegeQuery
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:326
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:326

use_synonym_extension
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:237

uuid
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:260
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:73

value
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:52
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:59
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:66
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:547
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:635
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:139
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:146
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:151

*/
