/**
 * @file sf1r/driver/Keys.inl
 * @date Created <2014-07-10 16:36:47>
 *
 * This file is generated by generators/driver_keys.rb by collecting keys
 * from source code. Do not edit this file directly.
 */

#define SF1_DRIVER_KEYS \
(DOCID)\
(DistributeStatus)\
(MemoryStatus)\
(USERID)\
(_ad_click_cost)\
(_ad_hit_bidstr)\
(_ctr)\
(_custom_rank)\
(_duplicated_document_count)\
(_geo_dist)\
(_id)\
(_rank)\
(_tid)\
(ad_campaign)\
(ad_keyword)\
(ad_search)\
(algorithm)\
(analyzer)\
(analyzer_result)\
(apply_la)\
(attr)\
(attr_label)\
(attr_name)\
(attr_result)\
(attr_top)\
(attr_value)\
(attr_values)\
(auto_select_limit)\
(bidbudget)\
(bidphrase)\
(bidprice)\
(boost_group_label)\
(category)\
(category_score)\
(clear)\
(clustering_path)\
(collection)\
(collection_config)\
(condition_array)\
(conditions)\
(context)\
(count)\
(counter)\
(custom_rank)\
(disable_sharding)\
(document_count)\
(elapsed_time)\
(errors)\
(expression)\
(filter_mode)\
(force_backup)\
(freq)\
(func)\
(fuzzy_threshold)\
(geolocation)\
(group)\
(group_label)\
(group_property)\
(grouptop)\
(highlight)\
(id)\
(in)\
(index)\
(index_scd_path)\
(is_online_ad)\
(is_random_rank)\
(is_require_related)\
(keywords)\
(label)\
(labels)\
(last_modified)\
(latitude)\
(left_time)\
(limit)\
(log_keywords)\
(longitude)\
(lucky)\
(max)\
(merchant)\
(meta)\
(min)\
(mining)\
(mode)\
(name)\
(name_entity_item)\
(name_entity_type)\
(offset)\
(operator_)\
(order)\
(original_query)\
(params)\
(pos)\
(privilege_Query)\
(privilege_Weight)\
(progress)\
(property)\
(query)\
(query_prune)\
(query_source)\
(range)\
(rank)\
(ranking_model)\
(recommend)\
(refined_query)\
(related_queries)\
(relation)\
(remote_ip)\
(remove_duplicated_result)\
(resource)\
(resources)\
(score)\
(search)\
(search_session)\
(searching_mode)\
(select)\
(session_id)\
(snippet)\
(sort)\
(split_property_value)\
(status)\
(sub_labels)\
(sub_property)\
(summary)\
(summary_property_alias)\
(summary_sentence_count)\
(taxonomy_label)\
(text)\
(threshold)\
(title)\
(tokens_threshold)\
(top_group_label)\
(top_k_count)\
(topn)\
(total_count)\
(type)\
(unit)\
(use_fuzzy)\
(use_fuzzyThreshold)\
(use_original_keyword)\
(use_pivilegeQuery)\
(use_synonym_extension)\
(uuid)\
(value)


/* LOCATIONS

DOCID
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:144
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:146
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:196
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:222
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:61
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:86
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:108
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:670
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:776

DistributeStatus
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:106

MemoryStatus
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:107

USERID
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:156
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:674

_ad_click_cost
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:199

_ad_hit_bidstr
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:203

_ctr
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:150

_custom_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:210

_duplicated_document_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:121

_geo_dist
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:215

_id
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:139
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:141
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:196
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:214
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:113
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:149
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:195

_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:196

_tid
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:128

ad_campaign
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:32

ad_keyword
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:56

ad_search
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:628

algorithm
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:353
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:355

analyzer
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:234

analyzer_result
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:535
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:555

apply_la
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:235

attr
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:261
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:689

attr_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:597

attr_name
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:611
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:300
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/SplitPropValueRenderer.cpp:97

attr_result
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:28
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:30

attr_top
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:33
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/AttrParser.cpp:35

attr_value
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:612

attr_values
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/SplitPropValueRenderer.cpp:99

auto_select_limit
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:578

bidbudget
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:32

bidphrase
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:43
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:72

bidprice
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:58

boost_group_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:658

category
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:74
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:31

category_score
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:49
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:23

clear
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:226
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:228

clustering_path
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:194
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:201

collection
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:169
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:27
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:126
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:224
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:301
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:321
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:506
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:580
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:728
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:784
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:842
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:967
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:60
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:90
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:26

collection_config
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:843

condition_array
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/ConditionTreeParser.cpp:72

conditions
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:184
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:229

context
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:678
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:680
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:682

count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:183
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:718
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:736
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:771

counter
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:87

custom_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:233
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:236

disable_sharding
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:77

document_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:70
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:85
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:74
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:265
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:271
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:301
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:311

elapsed_time
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:81

errors
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:75
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:96
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:80

expression
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:90
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:91

filter_mode
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:442
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:444

force_backup
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:680

freq
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:565

func
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/SelectFieldParser.cpp:32

fuzzy_threshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:303
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:305

geolocation
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:240
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:249

group
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:257
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:684

group_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:533
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:567
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:826
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:840
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:336

group_property
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:813
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:335

grouptop
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:60

highlight
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:182

id
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:72

in
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:463

index
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:67

index_scd_path
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CollectionController.cpp:753
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/CommandsController.cpp:79

is_online_ad
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:109

is_random_rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:179

is_require_related
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:180

keywords
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:149
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:799

label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:270
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:310

labels
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:266
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:303

last_modified
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:69
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:86
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:93
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:100

latitude
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GeoLocationRankingParser.cpp:42

left_time
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:82

limit
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:20
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:22
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:546
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:787
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:789

log_keywords
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:178

longitude
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GeoLocationRankingParser.cpp:43

lucky
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:420
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:422

max
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:707

merchant
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:25
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:20

meta
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:83

min
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:706

mining
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:91

mode
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:268
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:270

name
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:125

name_entity_item
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:163

name_entity_type
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:164

offset
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:15
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/PageInfoParser.cpp:17

operator_
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:70

order
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/OrderParser.cpp:23

original_query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:433
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:435

params
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:79
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:80

pos
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:682

privilege_Query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:329
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:331

privilege_Weight
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:335
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:337

progress
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:80

property
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:45
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/OrderParser.cpp:22
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/SelectFieldParser.cpp:30
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:181
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GeoLocationRankingParser.cpp:21
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:194
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:480
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:547
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:642
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:57
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/RangeParser.cpp:36
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/ConditionTreeParser.cpp:85
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:763
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:264

query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:678

query_prune
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:275
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:275
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:295
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:295

query_source
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:158

range
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:62
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:64
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:265
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:705

rank
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:680

ranking_model
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:241
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:243

recommend
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:70
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:75

refined_query
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:730

related_queries
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:679

relation
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/ConditionTreeParser.cpp:73

remote_ip
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:26
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:59
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:89
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:25

remove_duplicated_result
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:534

resource
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/Sf1Controller.cpp:220
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:31
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:42
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:71
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/AdController.cpp:96
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:285
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:328
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:384
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:425
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:545
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:670
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:674
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:676
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:678
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:680
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:682
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:776
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:797
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:811
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:825
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:839

resources
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:46
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:68
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:309
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:328
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:360
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:656
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:667
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:47
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:560

score
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:302
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:312
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:32
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreParser.cpp:96
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:21
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/mining-manager/merchant-score-manager/MerchantScoreRenderer.cpp:29

search
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:211

search_session
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:98
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:101

searching_mode
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:267

select
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:55
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:79
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:225
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:56

session_id
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:157
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsController.cpp:676

snippet
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:196

sort
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:245

split_property_value
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:184

status
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:68
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:76
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:92
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/StatusController.cpp:98

sub_labels
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/renderers/DocumentsRenderer.cpp:272

sub_property
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:58

summary
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:185

summary_property_alias
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:193

summary_sentence_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SelectParser.cpp:189

taxonomy_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:161

text
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:76

threshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:407
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:409

title
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:71

tokens_threshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:314
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:316

top_group_label
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:694

top_k_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:139

topn
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/SlimHandler.cpp:73
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/LaserHandler.cpp:77

total_count
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:68
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:360
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsSearchHandler.cpp:132

type
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:138

unit
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/GroupingParser.cpp:59

use_fuzzy
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:438
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:440

use_fuzzyThreshold
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:300
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:300

use_original_keyword
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:236

use_pivilegeQuery
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:326
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:326

use_synonym_extension
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:237

uuid
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/controllers/DocumentsGetHandler.cpp:260

value
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:52
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:59
  /home/kevinlin/codebase/sf1r-ad-delivery/source/core/common/parsers/ConditionParser.cpp:66
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:555
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/SearchParser.cpp:643
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:139
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:146
  /home/kevinlin/codebase/sf1r-ad-delivery/source/process/parsers/CustomRankingParser.cpp:151

*/
